### ISSUE TITLE
clone and cmake but compile error

### ISSUE THREAD

**Issue by hotpeperoncino** [mpapierski/http-server#4]
$ mkdir build
$ cd build
$ cmake ..
-- The C compiler identification is GNU 4.9.4
-- The CXX compiler identification is GNU 4.9.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for select
-- Looking for select - found
-- Looking for kqueue
-- Looking for kqueue - not found
-- Configuring done
CMake Error at deps/CMakeLists.txt:1 (add_library):
  Cannot find source file:

    http-parser/http_parser.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: Cannot determine link language for target "http_parser".
CMake Error: CMake can not determine linker language for target: http_parser

**Comment by mpapierski** [comment]
Hi! Thanks for using this library. Did you clone with all submodules? Try this:

```sh
git submodule update --init
```

**Comment by hotpeperoncino** [comment]
Thanks.  I noticed it.. sorry.

**Comment by hotpeperoncino** [comment]
Probably it was not found. The url looks changed. But I have no problem..
